"use client";

import Image from "next/image";
import {
  ArrowDown,
  ArrowUpRight,
  Check,
  CircleCheck,
  Copy,
  Download,
  GitFork,
  ImageIcon,
  Layers3,
  LockKeyhole,
  RotateCcw,
  Route,
  ShieldCheck,
  Terminal,
} from "lucide-react";
import { useState } from "react";

const githubUrl = "https://github.com/yuyou-dev/ChatGPT-Bridge";
const releaseUrl = `${githubUrl}/releases`;
const installCommand =
  "codex plugin marketplace add yuyou-dev/ChatGPT-Bridge\ncodex plugin add chatgpt-bridge@chatgpt-bridge";

const routes = [
  {
    id: "temporary",
    label: "Temporary",
    action: "new_temporary",
    title: "Disposable text work",
    copy: "Supported one-turn text tasks can use Temporary Chat when they need no history, files, research, or image tools.",
    example: "Use Temporary Chat to tighten this product title.",
    accent: "acid",
  },
  {
    id: "standard",
    label: "Standard",
    action: "new_standard",
    title: "Images, batches, research",
    copy: "Image generation and persistent work open in a clean standard chat. The bridge waits for the intended output count before export.",
    example: "Generate 9 independent training cards, not a collage.",
    accent: "blue",
  },
  {
    id: "reuse",
    label: "Reuse",
    action: "reuse_current",
    title: "Context that must survive",
    copy: "Current history, attachments, and bounded Retry recovery stay in the selected conversation instead of starting over.",
    example: "Revise the last image using the attached reference.",
    accent: "red",
  },
  {
    id: "blocked",
    label: "Blocked",
    action: "blocked",
    title: "Fail closed, visibly",
    copy: "Explicit Temporary Chat requests are blocked when the verified surface cannot provide the required capability. No silent mode switch.",
    example: "Temporary Chat + image generation is currently blocked.",
    accent: "black",
  },
];

const proofFacts = [
  ["13 / 13", "targeted plugin tests"],
  ["19 / 19", "routing benchmark cases"],
  ["1", "bounded Retry recovery"],
  ["SHA-256", "for every exported asset"],
];

function CopyInstall() {
  const [copied, setCopied] = useState(false);

  async function copy() {
    await navigator.clipboard.writeText(installCommand);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  }

  return (
    <div className="install-shell" aria-label="Installation commands">
      <div className="install-shell__bar">
        <span>terminal / install</span>
        <button className="icon-button" onClick={copy} title="Copy install commands">
          {copied ? <Check size={18} /> : <Copy size={18} />}
          <span>{copied ? "Copied" : "Copy"}</span>
        </button>
      </div>
      <pre>
        <code>{installCommand}</code>
      </pre>
    </div>
  );
}

export default function Home() {
  const [activeRoute, setActiveRoute] = useState(routes[0]);

  return (
    <main>
      <header className="masthead">
        <a className="wordmark" href="#top" aria-label="ChatGPT Bridge home">
          <span className="wordmark__mark">CB</span>
          <span>ChatGPT Bridge</span>
        </a>
        <nav aria-label="Primary navigation">
          <a href="#routing">Routing</a>
          <a href="#proof">Proof</a>
          <a href="#install">Install</a>
          <a className="nav-github" href={githubUrl} target="_blank" rel="noreferrer">
            <GitFork size={17} />
            GitHub
          </a>
        </nav>
      </header>

      <section className="hero" id="top">
        <div className="hero__copy">
          <p className="kicker">
            <span>Open source</span>
            <span>MIT</span>
            <span>Codex plugin</span>
          </p>
          <h1>
            ChatGPT
            <br />
            Bridge
          </h1>
          <p className="hero__lede">
            Route work from Codex into your own signed-in ChatGPT web session.
            Generate, verify, and export original image assets without an API key.
          </p>
          <div className="hero__actions">
            <a className="button button--ink" href={githubUrl} target="_blank" rel="noreferrer">
              <GitFork size={19} />
              View source
              <ArrowUpRight size={18} />
            </a>
            <a className="button button--paper" href="#install">
              Install in Codex
              <ArrowDown size={18} />
            </a>
          </div>
        </div>

        <div className="hero__visual" aria-label="A verified image generated through ChatGPT Bridge">
          <div className="hero__issue">ISSUE 002 / WEB SESSION AUTOMATION</div>
          <Image
            src="/assets/bridge-output.png"
            alt="A green bridge symbol generated by ChatGPT and exported as an original image asset"
            width={1254}
            height={1254}
            priority
            unoptimized
          />
          <div className="hero__caption">
            <span>actual export</span>
            <span>1254 × 1254 PNG</span>
          </div>
        </div>
      </section>

      <section className="ticker" aria-label="Key features">
        <span>WEB SESSION, NOT API</span>
        <span>ORIGINAL ASSET EXPORT</span>
        <span>EXPECTED-COUNT WAITER</span>
        <span>RETRY-AWARE</span>
        <span>PORTABLE MANIFEST</span>
      </section>

      <section className="manifesto band" id="routing">
        <div className="section-index">
          <span>01</span>
          <span>ROUTE THE WORK</span>
        </div>
        <div className="manifesto__intro">
          <p className="eyebrow">Conservative by design</p>
          <h2>The conversation mode is part of the job.</h2>
          <p>
            ChatGPT Bridge decides where a request belongs before typing or uploading.
            Explicit constraints are honored; ambiguous work defaults to a clean standard chat.
          </p>
        </div>

        <div className="route-switcher">
          <div className="route-tabs" role="tablist" aria-label="Conversation routing modes">
            {routes.map((route) => (
              <button
                key={route.id}
                className={activeRoute.id === route.id ? "is-active" : ""}
                onClick={() => setActiveRoute(route)}
                role="tab"
                aria-selected={activeRoute.id === route.id}
              >
                <span>{route.label}</span>
                <small>{route.action}</small>
              </button>
            ))}
          </div>
          <div className={`route-panel route-panel--${activeRoute.accent}`}>
            <div>
              <Route size={31} strokeWidth={1.6} />
              <p className="route-panel__action">{activeRoute.action}</p>
            </div>
            <div>
              <h3>{activeRoute.title}</h3>
              <p>{activeRoute.copy}</p>
            </div>
            <blockquote>{activeRoute.example}</blockquote>
          </div>
        </div>
      </section>

      <section className="proof band" id="proof">
        <div className="section-index section-index--light">
          <span>02</span>
          <span>PROOF, NOT PROMISES</span>
        </div>
        <div className="proof__header">
          <p className="eyebrow">Last verified 2026-07-24</p>
          <h2>Measured at the saved bytes.</h2>
          <p>
            Page assets are exported from the ChatGPT surface, then measured locally.
            Screenshot dimensions and requested ratios are never treated as authoritative.
          </p>
        </div>
        <div className="proof__spread">
          <div className="proof__image">
            <Image
              src="/assets/chatgpt-proof.png"
              alt="ChatGPT standard conversation showing a completed bridge image"
              width={1800}
              height={1520}
              unoptimized
            />
            <span className="tape-label">standard chat / image route</span>
          </div>
          <div className="proof__facts">
            {proofFacts.map(([value, label]) => (
              <div key={label}>
                <strong>{value}</strong>
                <span>{label}</span>
              </div>
            ))}
          </div>
        </div>
        <p className="proof__note">
          The guided batch workflow supports up to 9 independent outputs. Actual availability,
          count, and limits depend on the signed-in ChatGPT account and current product surface.
        </p>
      </section>

      <section className="pipeline band">
        <div className="section-index">
          <span>03</span>
          <span>THE BRIDGE</span>
        </div>
        <div className="pipeline__headline">
          <h2>From request to reviewable file.</h2>
          <p>No hidden service. No proxy subscription. No screenshot pretending to be an asset.</p>
        </div>
        <ol className="pipeline__steps">
          <li>
            <Terminal size={25} />
            <span>01</span>
            <h3>Ask in Codex</h3>
            <p>Describe a one-off text job, a single image, or a coherent batch.</p>
          </li>
          <li>
            <LockKeyhole size={25} />
            <span>02</span>
            <h3>Use your session</h3>
            <p>Sign in yourself inside the Codex in-app browser. Credentials stay on ChatGPT.</p>
          </li>
          <li>
            <ImageIcon size={25} />
            <span>03</span>
            <h3>Wait for fresh assets</h3>
            <p>The waiter observes completion, expected count, text-only replies, and retry errors.</p>
          </li>
          <li>
            <Download size={25} />
            <span>04</span>
            <h3>Export originals</h3>
            <p>Save page assets locally, record dimensions and checksums, then mark Needs Review.</p>
          </li>
        </ol>
      </section>

      <section className="recovery band">
        <div className="recovery__copy">
          <p className="eyebrow">Failure is a state, not a spinner</p>
          <h2>It sees Retry. It does not wait forever.</h2>
          <p>
            When ChatGPT displays a retryable response error, the bridge clicks one unique Retry
            control, verifies the intended mode, and checks whether the prompt became an unsent draft.
            A second failure returns a structured <code>retry_exhausted</code> result.
          </p>
          <div className="recovery__status">
            <RotateCcw size={20} />
            bounded recovery / one verified attempt
          </div>
        </div>
        <div className="recovery__image">
          <Image
            src="/assets/retry-proof.png"
            alt="ChatGPT retryable error state observed by the bridge benchmark"
            width={1800}
            height={1520}
            unoptimized
          />
        </div>
      </section>

      <section className="install band" id="install">
        <div className="section-index">
          <span>04</span>
          <span>THREE-MINUTE START</span>
        </div>
        <div className="install__grid">
          <div className="install__copy">
            <p className="eyebrow">Codex desktop + in-app browser</p>
            <h2>Add. Verify. Start fresh.</h2>
            <ol>
              <li>
                <span>1</span>
                <p>Run the two install commands.</p>
              </li>
              <li>
                <span>2</span>
                <p>
                  Verify with <code>codex plugin list</code>.
                </p>
              </li>
              <li>
                <span>3</span>
                <p>Start a new Codex task so the skill loads.</p>
              </li>
              <li>
                <span>4</span>
                <p>Sign in to ChatGPT yourself when the in-app browser opens.</p>
              </li>
            </ol>
          </div>
          <CopyInstall />
        </div>
        <div className="first-run">
          <div>
            <CircleCheck size={24} />
            <span>Temporary text test</span>
            <code>Use Temporary Chat to rewrite this title more concisely.</code>
          </div>
          <div>
            <Layers3 size={24} />
            <span>Standard image test</span>
            <code>Generate one 3:4 editorial image and export the original.</code>
          </div>
        </div>
      </section>

      <section className="trust band">
        <div className="trust__statement">
          <ShieldCheck size={42} strokeWidth={1.5} />
          <h2>Your sign-in stays between you and ChatGPT.</h2>
        </div>
        <div className="trust__details">
          <p>
            Passwords, passkeys, CAPTCHA, verification codes, cookies, and session tokens are not
            read or exported by the plugin.
          </p>
          <p>
            Prompts and explicitly selected reference files are sent to ChatGPT because the work runs
            on chatgpt.com. Shareable manifests omit prompts, conversation URLs, absolute paths, and
            temporary asset URLs by default.
          </p>
          <a href={`${githubUrl}/blob/main/docs/LOGIN.md`} target="_blank" rel="noreferrer">
            Read the login and privacy guide
            <ArrowUpRight size={17} />
          </a>
        </div>
      </section>

      <section className="final-cta">
        <div>
          <p className="eyebrow">Open source / unofficial / MIT</p>
          <h2>Bridge the browser. Keep the evidence.</h2>
        </div>
        <div className="final-cta__actions">
          <a className="button button--acid" href={githubUrl} target="_blank" rel="noreferrer">
            <GitFork size={20} />
            Explore the repository
            <ArrowUpRight size={18} />
          </a>
          <a href={releaseUrl} target="_blank" rel="noreferrer">
            Latest release
            <ArrowUpRight size={16} />
          </a>
        </div>
      </section>

      <footer>
        <div>
          <strong>ChatGPT Bridge</strong>
          <span>Open-source Codex plugin</span>
        </div>
        <p>
          Unofficial. Not affiliated with or endorsed by OpenAI. ChatGPT availability, account limits,
          and product behavior may change.
        </p>
        <a href={githubUrl} target="_blank" rel="noreferrer">
          GitHub <ArrowUpRight size={14} />
        </a>
      </footer>
    </main>
  );
}
